name: BedHome
main: dev.blackmc.bedhome.BedHome
version: 1.1
api-version: 1.17
commands:
  home:
    description: Teleport to your bed.
    usage: /home bed
    permission: bedhome.bed
    permission-message: You do not have permission to use this command.
  bedhome:
    description: BedHome plugin management commands.
    usage: /bedhome reload
    aliases: [bh]
    permission: bedhome.admin
    permission-message: You do not have permission to use this command.
permissions:
  bedhome.bed:
    description: Allows the player to use the /home bed command.
    default: true
  bedhome.admin:
    description: Allows the player to reload the plugin configuration.
    default: op
